language: ruby

git:
  submodules: false

env:
  global:
  - AWS_DEFAULT_REGION=us-west-2 
  
before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - echo "Installing test gems"
  - gem install yaml-lint

install: true

script:
  - aws cloudformation validate-template --template-body file://templates/elb-to-ec2-target-group-cf-template.yaml
  - yaml-lint templates/elb-to-ec2-target-group-cf-template.yaml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation template validated"
  - echo "YAML linted"
