AWSTemplateFormatVersion: 2010-09-09
Description: Creates a certificate for manual dns verification

Parameters:

    DomainName:
        Description: 'FQDN for certificate'
        Type: String

Resources:

    Certificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: 
          Ref: DomainName
        DomainValidationOptions:
          - DomainName: 
              Ref: DomainName
            ValidationDomain: 
              Ref: DomainName
        SubjectAlternativeNames:
          - !Join
            - '.' 
            - - '*' # wildcard for subdomains
              - !Ref DomainName 
        ValidationMethod: DNS

Outputs:

    CertificateArn:
        Description: 'ARN of certificate to attach to domain'
        Value: !Ref Certificate
        Export:
          Name: !Sub '${AWS::Region}-${AWS::StackName}-CertificateArn'
