# Setting up a certificate requires a manual step to enter the DNS Validation on godaddy.
Description: Setup an ACM Certificate
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DomainName:
    Description: Domain name
    Type: String
  SubDomainName:
    Description: Sub-domain name
    Type: String
    Default: "*" #default to wildcard cert
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join
        - '.'
        - - !Ref SubDomainName
          - !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Join
            - '.'
            - - !Ref SubDomainName
              - !Ref DomainName
          ValidationDomain: !Ref DomainName
      ValidationMethod: "DNS"
Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-CertificateArn'
