Description: IAM Resources for EC2
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ManagedInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
                - "ssm.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
  ManagedInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: "/"
      Roles:
        - !Ref ManagedInstanceRole
Outputs:
  ManagedInstanceProfile:
    Description: Profile to allow instances to tag its root volume and allow SSM actions
    Value: !Ref ManagedInstanceProfile
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ManagedInstanceProfile'
  ManagedInstanceProfileArn:
    Description: Profile to allow instances to tag its root volume and allow SSM actions
    Value: !GetAtt ManagedInstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ManagedInstanceProfileArn'
  ManagedInstanceRole:
    Description: Role to allow instances to tag its root volume and allow SSM actions
    Value: !Ref ManagedInstanceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ManagedInstanceRole'
  ManagedInstanceRoleArn:
    Description: Role to allow instances to tag its root volume and allow SSM actions
    Value: !GetAtt ManagedInstanceRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ManagedInstanceRoleArn'
